vendor/bin/sauce_config $SAUCE_LABS_USERNAME $SAUCE_LABS_ACCESS_KEY
export SELENIUM_ENV='DEV'
#//config
#vendor/bin/phpunit convert/add_inventory.php
#vendor/bin/phpunit convert/add_inventory_error_booking_rooms.php
#vendor/bin/phpunit convert/event_canceletion.php
#vendor/bin/phpunit convert/calendar_out_of_service.php
#vendor/bin/phpunit convert/comon_features.php
#vendor/bin/phpunit convert/calendar_change_price.php
#vendor/bin/phpunit convert/charge_adults_ide.php
#vendor/bin/phpunit convert/availability_backend.php
#vendor/bin/phpunit convert/availability_booking.php
#// new
##vendor/bin/phpunit convert/ma_add_interval_for_ma.php
##vendor/bin/phpunit convert/ma_change_rate_on_one_day.php
##vendor/bin/phpunit convert/bulk_action_reservation.php
#vendor/bin/phpunit convert/booking_availability.php
#vendor/bin/phpunit convert/cash_drawers.php
#vendor/bin/phpunit convert/reservation_edit_price.php
##vendor/bin/phpunit convert/calendar_room_blocks.php
#vendor/bin/phpunit convert/import_bulk_reservation.php
##vendor/bin/phpunit convert/house_keeping.php
##vendor/bin/phpunit convert/availability_matrix_intervals.php
##vendor/bin/phpunit convert/house_account.php
##vendor/bin/phpunit convert/additional_payment_methods.php
#vendor/bin/phpunit convert/additional_guest_regcard.php
#vendor/bin/phpunit convert/copy_intervals.php
######vendor/bin/phpunit convert/add_inventory_room_error.php
#vendor/bin/phpunit convert/hotel_profile_ciry_error.php
##vendor/bin/phpunit convert/add_interval_date_error.php
####vendor/bin/phpunit convert/Do_you_charge_for_additional_adults_and_or_children.php
#vendor/bin/phpunit convert/fAdd_min_max_rate.php
#vendor/bin/phpunit convert/fUpdate_rate.php
#vendor/bin/phpunit convert/booking_to_cache.php
#vendor/bin/phpunit convert/room_block_booking.php
#vendor/bin/phpunit convert/packages_availability.php
#vendor/bin/phpunit convert/packages_availability_for_OTA.php
#vendor/bin/phpunit convert/customize_emails_readonly_area_lang_changed.php
#vendor/bin/phpunit convert/derived_plan_should_show_additioinal_label_on_booking.php
###vendor/bin/phpunit convert/addons_for_PMS.php
###vendor/bin/phpunit convert/addons_for_OTA.php
#vendor/bin/phpunit convert/invoice.php
#vendor/bin/phpunit convert/guest_status.php
#vendor/bin/phpunit convert/rebuild_cache.php
#vendor/bin/phpunit convert/dashboard_for_PMS.php
#vendor/bin/phpunit convert/calendar_balance_due.php
#vendor/bin/phpunit convert/closed_arrival_departure.php
##vendor/bin/phpunit convert/no_collect_deposit.php